I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


File "game/script.rpy", line 836: end of line expected.
    uai "You shouldn't take revenge on me!":
                                           ^

Ren'Py Version: Ren'Py 7.3.5.606
Sun Dec 06 21:53:52 2020
